linters:
  Indentation:
    severity: warning
    width: 4
  NestingDepth:
    enabled: false
  Comment:
    enabled: false
  SelectorDepth:
    enabled: false
  DeclarationOrder:
    enabled: false
  PropertySortOrder:
    enabled: false