language: node_js
node_js:
- '6'
install:
- npm install
script:
- node app/crawler
- grunt prod
before_install:
- openssl aes-256-cbc -K $encrypted_3519e5c09549_key -iv $encrypted_3519e5c09549_iv
  -in app/credentials.js.enc -out app/credentials.js -d
